language: go

go:
  - 1.6
  
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/andrewbackes/chess/pgn
  - go get github.com/andrewbackes/chess/book
  
script:
  - ./test.sh
  - goveralls -coverprofile=total.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN