language: go

go:
  - 1.6
  
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go list -f '{{range .TestImports}}{{.}}\n{{end}}' PACKAGE | xargs go get 
  
script:
  - ./test.sh
  - goveralls -coverprofile=total.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN